"""create_initial_tables

Revision ID: 4dcbe7c548c4
Revises: 
Create Date: 2026-09-22 12:04:58.093228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4dcbe7c548c4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.Text(), nullable=False),
    sa.Column('resource_id', sa.Text(), nullable=True),
    sa.Column('workspace_type', sa.Text(), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False, comment='success | failure | error'),
    sa.Column('changed_from', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Previous state before the action'),
    sa.Column('changed_to', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='New state after the action'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('cost_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('owner_type', sa.Text(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('level', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('family', sa.Text(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_items_project_id'), 'cost_items', ['project_id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_code', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('date_of_birth', sa.Text(), nullable=False),
    sa.Column('gender', sa.Text(), nullable=False),
    sa.Column('blood_group', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('phone_number', sa.Text(), nullable=False),
    sa.Column('emergency_contact_name', sa.Text(), nullable=False),
    sa.Column('emergency_contact_phone', sa.Text(), nullable=False),
    sa.Column('address_line1', sa.Text(), nullable=False),
    sa.Column('address_line2', sa.Text(), nullable=False),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('pincode', sa.Text(), nullable=False),
    sa.Column('country', sa.Text(), nullable=False),
    sa.Column('designation', sa.Text(), nullable=False),
    sa.Column('department', sa.Text(), nullable=False),
    sa.Column('employment_type', sa.Text(), nullable=False),
    sa.Column('date_of_joining', sa.Text(), nullable=False),
    sa.Column('reporting_manager', sa.Text(), nullable=False),
    sa.Column('site_assigned', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('salary_type', sa.Text(), nullable=False),
    sa.Column('base_salary', sa.Text(), nullable=False),
    sa.Column('bank_name', sa.Text(), nullable=False),
    sa.Column('account_number', sa.Text(), nullable=False),
    sa.Column('ifsc_code', sa.Text(), nullable=False),
    sa.Column('aadhaar_number', sa.Text(), nullable=False),
    sa.Column('pan_number', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_employee_code'), 'employees', ['employee_code'], unique=True)
    op.create_table('equipment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('equipment_code', sa.Text(), nullable=False),
    sa.Column('equipment_name', sa.Text(), nullable=False),
    sa.Column('equipment_type', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('brand', sa.Text(), nullable=False),
    sa.Column('make', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('model_number', sa.Text(), nullable=False),
    sa.Column('serial_number', sa.Text(), nullable=False),
    sa.Column('year_of_manufacture', sa.Text(), nullable=False),
    sa.Column('ownership_type', sa.Text(), nullable=False),
    sa.Column('vendor', sa.Text(), nullable=False),
    sa.Column('weight', sa.Text(), nullable=False),
    sa.Column('capacity', sa.Text(), nullable=False),
    sa.Column('power_rating', sa.Text(), nullable=False),
    sa.Column('current_site', sa.Text(), nullable=False),
    sa.Column('assigned_project', sa.Text(), nullable=False),
    sa.Column('assigned_site_location', sa.Text(), nullable=False),
    sa.Column('assigned_to', sa.Text(), nullable=False),
    sa.Column('operator_assigned', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('current_status', sa.Text(), nullable=False),
    sa.Column('purchase_date', sa.Text(), nullable=False),
    sa.Column('purchase_cost', sa.Text(), nullable=False),
    sa.Column('rental_end_date', sa.Text(), nullable=False),
    sa.Column('warranty_expiry', sa.Text(), nullable=False),
    sa.Column('warranty_expiry_date', sa.Text(), nullable=False),
    sa.Column('last_maintenance', sa.Text(), nullable=False),
    sa.Column('last_maintenance_date', sa.Text(), nullable=False),
    sa.Column('next_maintenance', sa.Text(), nullable=False),
    sa.Column('next_maintenance_due', sa.Text(), nullable=False),
    sa.Column('maintenance_interval', sa.Text(), nullable=False),
    sa.Column('maintenance_log', sa.Text(), nullable=False),
    sa.Column('depreciation_rate', sa.Text(), nullable=False),
    sa.Column('current_value', sa.Text(), nullable=False),
    sa.Column('insurance_provider', sa.Text(), nullable=False),
    sa.Column('insurance_expiry', sa.Text(), nullable=False),
    sa.Column('insurance_expiry_date', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_equipment_code'), 'equipment', ['equipment_code'], unique=True)
    op.create_table('ifc_meetings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_type', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.Text(), nullable=False),
    sa.Column('meeting_code', sa.Text(), nullable=True),
    sa.Column('group_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('member_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('custom_members', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ifc_meetings_owner_id'), 'ifc_meetings', ['owner_id'], unique=False)
    op.create_index(op.f('ix_ifc_meetings_owner_type'), 'ifc_meetings', ['owner_type'], unique=False)
    op.create_table('materials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('material_code', sa.Text(), nullable=False),
    sa.Column('material_name', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('grade', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('unit_of_measurement', sa.Text(), nullable=False),
    sa.Column('current_stock', sa.Text(), nullable=False),
    sa.Column('minimum_stock', sa.Text(), nullable=False),
    sa.Column('reorder_level', sa.Text(), nullable=False),
    sa.Column('supplier_name', sa.Text(), nullable=False),
    sa.Column('supplier_contact', sa.Text(), nullable=False),
    sa.Column('lead_time_days', sa.Text(), nullable=False),
    sa.Column('storage_location', sa.Text(), nullable=False),
    sa.Column('storage_condition', sa.Text(), nullable=False),
    sa.Column('batch_number', sa.Text(), nullable=False),
    sa.Column('expiry_date', sa.Text(), nullable=False),
    sa.Column('purchase_rate', sa.Text(), nullable=False),
    sa.Column('total_value', sa.Text(), nullable=False),
    sa.Column('hsn_code', sa.Text(), nullable=False),
    sa.Column('gst_rate', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_material_code'), 'materials', ['material_code'], unique=True)
    op.create_table('qto_custom_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('owner_type', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('family', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('net_surface_area', sa.Float(), nullable=True),
    sa.Column('outer_surface_area', sa.Float(), nullable=True),
    sa.Column('net_volume', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qto_custom_items_project_id'), 'qto_custom_items', ['project_id'], unique=False)
    op.create_table('scheduling_task_element_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.Text(), nullable=False),
    sa.Column('element_global_id', sa.Text(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduling_task_element_links_project_id'), 'scheduling_task_element_links', ['project_id'], unique=False)
    op.create_index(op.f('ix_scheduling_task_element_links_task_id'), 'scheduling_task_element_links', ['task_id'], unique=False)
    op.create_table('scheduling_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('owner_type', sa.Text(), nullable=False),
    sa.Column('task_id', sa.Text(), nullable=False),
    sa.Column('level', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Text(), nullable=False),
    sa.Column('end_date', sa.Text(), nullable=False),
    sa.Column('duration', sa.JSON(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('color', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Text(), nullable=True),
    sa.Column('predecessors', sa.Text(), nullable=True),
    sa.Column('predecessors_lag', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduling_tasks_order'), 'scheduling_tasks', ['order'], unique=False)
    op.create_index(op.f('ix_scheduling_tasks_project_id'), 'scheduling_tasks', ['project_id'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_type', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_monthly', sa.Integer(), nullable=False),
    sa.Column('price_yearly', sa.Integer(), nullable=False),
    sa.Column('stripe_price_id_monthly', sa.Text(), nullable=True),
    sa.Column('stripe_price_id_yearly', sa.Text(), nullable=True),
    sa.Column('max_workspaces', sa.Integer(), nullable=False),
    sa.Column('max_projects_per_workspace', sa.Integer(), nullable=False),
    sa.Column('max_members_per_workspace', sa.Integer(), nullable=False),
    sa.Column('max_members_per_project', sa.Integer(), nullable=False),
    sa.Column('max_storage_bytes', sa.BigInteger(), nullable=False),
    sa.Column('can_use_4d', sa.Boolean(), nullable=False),
    sa.Column('can_use_5d', sa.Boolean(), nullable=False),
    sa.Column('can_use_clash_detection', sa.Boolean(), nullable=False),
    sa.Column('can_export_bcf', sa.Boolean(), nullable=False),
    sa.Column('can_use_ai', sa.Boolean(), nullable=False),
    sa.Column('can_use_maintenance', sa.Boolean(), nullable=False),
    sa.Column('can_use_facility', sa.Boolean(), nullable=False),
    sa.Column('can_use_api', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cognito_sub', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('company_name', sa.Text(), nullable=True),
    sa.Column('job_title', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('timezone', sa.Text(), nullable=False),
    sa.Column('platform_role', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_onboarded', sa.Boolean(), nullable=False),
    sa.Column('is_default_onboarding', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivated_by', sa.UUID(), nullable=True),
    sa.Column('terms_accepted', sa.Boolean(), nullable=False),
    sa.Column('terms_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terms_version', sa.Text(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.Text(), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['deactivated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_cognito_sub'), 'users', ['cognito_sub'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vendors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_code', sa.Text(), nullable=False),
    sa.Column('vendor_name', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('vendor_type', sa.Text(), nullable=False),
    sa.Column('registration_number', sa.Text(), nullable=False),
    sa.Column('primary_contact_name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('phone_number', sa.Text(), nullable=False),
    sa.Column('alternate_phone', sa.Text(), nullable=False),
    sa.Column('website', sa.Text(), nullable=False),
    sa.Column('address_line1', sa.Text(), nullable=False),
    sa.Column('address_line2', sa.Text(), nullable=False),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('country', sa.Text(), nullable=False),
    sa.Column('pincode', sa.Text(), nullable=False),
    sa.Column('bank_name', sa.Text(), nullable=False),
    sa.Column('account_number', sa.Text(), nullable=False),
    sa.Column('ifsc_code', sa.Text(), nullable=False),
    sa.Column('payment_terms', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_vendor_code'), 'vendors', ['vendor_code'], unique=True)
    op.create_table('work_packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('owner_type', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('milestone_ids', sa.JSON(), nullable=True),
    sa.Column('team_ids', sa.JSON(), nullable=True),
    sa.Column('member_ids', sa.JSON(), nullable=True),
    sa.Column('statuses', sa.JSON(), nullable=True),
    sa.Column('folder_ids', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('start_date', sa.Text(), nullable=True),
    sa.Column('end_date', sa.Text(), nullable=True),
    sa.Column('visibility', sa.JSON(), nullable=True),
    sa.Column('tasks', sa.JSON(), nullable=True),
    sa.Column('milestones', sa.JSON(), nullable=True),
    sa.Column('ifc_file_id', sa.Text(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_packages_project_id'), 'work_packages', ['project_id'], unique=False)
    op.create_table('aim_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('max_aim_workspaces', sa.Integer(), nullable=False),
    sa.Column('max_projects_per_aim_workspace', sa.Integer(), nullable=False),
    sa.Column('max_members_per_workspace', sa.Integer(), nullable=False),
    sa.Column('max_members_per_project', sa.Integer(), nullable=False),
    sa.Column('can_use_ai', sa.Boolean(), nullable=False),
    sa.Column('can_use_api', sa.Boolean(), nullable=False),
    sa.Column('can_use_maintenance', sa.Boolean(), nullable=False),
    sa.Column('can_use_facility', sa.Boolean(), nullable=False),
    sa.Column('stripe_customer_id', sa.Text(), nullable=True),
    sa.Column('stripe_subscription_id', sa.Text(), nullable=True),
    sa.Column('stripe_price_id', sa.Text(), nullable=True),
    sa.Column('billing_period', sa.Text(), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('is_manually_overridden', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('overridden_by', sa.UUID(), nullable=True),
    sa.Column('overridden_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_customer_id'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    op.create_index(op.f('ix_aim_subscriptions_user_id'), 'aim_subscriptions', ['user_id'], unique=True)
    op.create_table('aim_workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aim_workspaces_owner_id'), 'aim_workspaces', ['owner_id'], unique=False)
    op.create_table('cde_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_type', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_ids', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cde_groups_owner_id'), 'cde_groups', ['owner_id'], unique=False)
    op.create_table('cde_naming_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'category', 'code', name='uq_cde_naming_code')
    )
    op.create_index(op.f('ix_cde_naming_codes_category'), 'cde_naming_codes', ['category'], unique=False)
    op.create_index(op.f('ix_cde_naming_codes_owner_id'), 'cde_naming_codes', ['owner_id'], unique=False)
    op.create_table('coupons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('discount_type', sa.Enum('percentage', 'flat', name='coupon_discount_type'), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'expired', 'disabled', 'archived', name='coupon_status'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupons_code'), 'coupons', ['code'], unique=True)
    op.create_table('modules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('product_type', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('pim_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('max_pim_workspaces', sa.Integer(), nullable=False),
    sa.Column('max_projects_per_pim_workspace', sa.Integer(), nullable=False),
    sa.Column('max_members_per_workspace', sa.Integer(), nullable=False),
    sa.Column('max_members_per_project', sa.Integer(), nullable=False),
    sa.Column('can_use_4d', sa.Boolean(), nullable=False),
    sa.Column('can_use_5d', sa.Boolean(), nullable=False),
    sa.Column('can_use_clash_detection', sa.Boolean(), nullable=False),
    sa.Column('can_export_bcf', sa.Boolean(), nullable=False),
    sa.Column('can_use_api', sa.Boolean(), nullable=False),
    sa.Column('stripe_customer_id', sa.Text(), nullable=True),
    sa.Column('stripe_subscription_id', sa.Text(), nullable=True),
    sa.Column('stripe_price_id', sa.Text(), nullable=True),
    sa.Column('billing_period', sa.Text(), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('is_manually_overridden', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('overridden_by', sa.UUID(), nullable=True),
    sa.Column('overridden_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_customer_id'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    op.create_index(op.f('ix_pim_subscriptions_user_id'), 'pim_subscriptions', ['user_id'], unique=True)
    op.create_table('pim_workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pim_workspaces_owner_id'), 'pim_workspaces', ['owner_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('product_type', sa.Text(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_editable', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_type', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storage_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bytes_used', sa.BigInteger(), nullable=False),
    sa.Column('bytes_limit', sa.BigInteger(), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_usage_user_id'), 'storage_usage', ['user_id'], unique=True)
    op.create_table('user_platform_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('permission_slug', sa.Text(), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'permission_slug', name='uq_user_platform_permission')
    )
    op.create_index(op.f('ix_user_platform_permissions_user_id'), 'user_platform_permissions', ['user_id'], unique=False)
    op.create_table('aim_workspace_members',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['aim_workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'user_id')
    )
    op.create_table('invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('workspace_type', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('disciplines', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('accepted_by', sa.UUID(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_by', sa.UUID(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['accepted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['revoked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitations_email'), 'invitations', ['email'], unique=False)
    op.create_index(op.f('ix_invitations_token'), 'invitations', ['token'], unique=True)
    op.create_table('pim_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('project_code', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('import_locked', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['pim_workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pim_projects_workspace_id'), 'pim_projects', ['workspace_id'], unique=False)
    op.create_table('pim_workspace_members',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['pim_workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'user_id')
    )
    op.create_table('submodules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_id', 'slug', name='uq_submodule_module_slug')
    )
    op.create_index(op.f('ix_submodules_module_id'), 'submodules', ['module_id'], unique=False)
    op.create_table('aim_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('asset_type', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('source_pim_project_id', sa.UUID(), nullable=True),
    sa.Column('handover_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_pim_project_id'], ['pim_projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['aim_workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aim_projects_workspace_id'), 'aim_projects', ['workspace_id'], unique=False)
    op.create_table('pim_project_members',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('is_share_only', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['pim_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    op.create_table('pim_scope_disciplines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('lead_user_id', sa.UUID(), nullable=True),
    sa.Column('color', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['pim_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pim_scope_disciplines_project_id'), 'pim_scope_disciplines', ['project_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('submodule_id', sa.UUID(), nullable=True),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('can_create', sa.Boolean(), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=False),
    sa.Column('can_delete', sa.Boolean(), nullable=False),
    sa.Column('can_approve', sa.Boolean(), nullable=False),
    sa.Column('can_share', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submodule_id'], ['submodules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'module_id', 'submodule_id', name='uq_role_module_submodule')
    )
    op.create_index(op.f('ix_role_permissions_module_id'), 'role_permissions', ['module_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_submodule_id'), 'role_permissions', ['submodule_id'], unique=False)
    op.create_table('aim_project_members',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('is_share_only', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['aim_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    op.create_table('cde_folders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_type', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('discipline_id', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['discipline_id'], ['pim_scope_disciplines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['cde_folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cde_folders_discipline_id'), 'cde_folders', ['discipline_id'], unique=False)
    op.create_index(op.f('ix_cde_folders_owner_id'), 'cde_folders', ['owner_id'], unique=False)
    op.create_index(op.f('ix_cde_folders_parent_id'), 'cde_folders', ['parent_id'], unique=False)
    op.create_table('pim_scope_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('discipline_id', sa.UUID(), nullable=True),
    sa.Column('element_name', sa.Text(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('lod_required', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['discipline_id'], ['pim_scope_disciplines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['pim_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pim_scope_items_discipline_id'), 'pim_scope_items', ['discipline_id'], unique=False)
    op.create_index(op.f('ix_pim_scope_items_project_id'), 'pim_scope_items', ['project_id'], unique=False)
    op.create_table('cde_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_type', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('folder_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('s3_key', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.Text(), nullable=False),
    sa.Column('file_extension', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_file_id', sa.UUID(), nullable=True),
    sa.Column('discipline', sa.Text(), nullable=True),
    sa.Column('document_number', sa.Text(), nullable=True),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_by', sa.UUID(), nullable=True),
    sa.Column('shared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shared_by', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['folder_id'], ['cde_folders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_file_id'], ['cde_files.id'], ),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shared_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('s3_key')
    )
    op.create_index(op.f('ix_cde_files_folder_id'), 'cde_files', ['folder_id'], unique=False)
    op.create_index(op.f('ix_cde_files_owner_id'), 'cde_files', ['owner_id'], unique=False)
    op.create_table('cde_folder_shares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('folder_id', sa.UUID(), nullable=False),
    sa.Column('shared_with', sa.UUID(), nullable=False),
    sa.Column('shared_by', sa.UUID(), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shared_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['folder_id'], ['cde_folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shared_with'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folder_id', 'shared_with', name='uq_cde_folder_shares_folder_user')
    )
    op.create_index(op.f('ix_cde_folder_shares_folder_id'), 'cde_folder_shares', ['folder_id'], unique=False)
    op.create_index(op.f('ix_cde_folder_shares_shared_with'), 'cde_folder_shares', ['shared_with'], unique=False)
    op.create_index(op.f('ix_cde_folder_shares_token'), 'cde_folder_shares', ['token'], unique=True)
    op.create_table('cde_pending_folder_shares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('folder_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=False),
    sa.Column('shared_by', sa.UUID(), nullable=False),
    sa.Column('shared_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attached_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attached_to', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['attached_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['folder_id'], ['cde_folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cde_pending_folder_shares_email'), 'cde_pending_folder_shares', ['email'], unique=False)
    op.create_index(op.f('ix_cde_pending_folder_shares_folder_id'), 'cde_pending_folder_shares', ['folder_id'], unique=False)
    op.create_table('cde_file_shares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('shared_with', sa.UUID(), nullable=False),
    sa.Column('shared_by', sa.UUID(), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shared_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['cde_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shared_with'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id', 'shared_with', name='uq_cde_file_shares_file_user')
    )
    op.create_index(op.f('ix_cde_file_shares_file_id'), 'cde_file_shares', ['file_id'], unique=False)
    op.create_index(op.f('ix_cde_file_shares_shared_with'), 'cde_file_shares', ['shared_with'], unique=False)
    op.create_index(op.f('ix_cde_file_shares_token'), 'cde_file_shares', ['token'], unique=True)
    op.create_table('cde_pending_file_shares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=False),
    sa.Column('shared_by', sa.UUID(), nullable=False),
    sa.Column('shared_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attached_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attached_to', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['attached_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['cde_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cde_pending_file_shares_email'), 'cde_pending_file_shares', ['email'], unique=False)
    op.create_index(op.f('ix_cde_pending_file_shares_file_id'), 'cde_pending_file_shares', ['file_id'], unique=False)
    op.create_table('gs_tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('position', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('camera', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['cde_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gs_tags_file_id'), 'gs_tags', ['file_id'], unique=False)
    op.create_table('ifc_imports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cde_file_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('celery_task_id', sa.Text(), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('glb_s3_key', sa.Text(), nullable=True),
    sa.Column('thumbnail_s3_key', sa.Text(), nullable=True),
    sa.Column('ifc_schema_version', sa.Text(), nullable=True),
    sa.Column('element_count', sa.Integer(), nullable=True),
    sa.Column('discipline', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['cde_file_id'], ['cde_files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ifc_imports_cde_file_id'), 'ifc_imports', ['cde_file_id'], unique=False)
    op.create_table('ifc_markers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['cde_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ifc_markers_file_id'), 'ifc_markers', ['file_id'], unique=False)
    op.create_table('ifc_measurements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['cde_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ifc_measurements_file_id'), 'ifc_measurements', ['file_id'], unique=False)
    op.create_table('ifc_selection_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('file_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('color', sa.Text(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['cde_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ifc_selection_groups_file_id'), 'ifc_selection_groups', ['file_id'], unique=False)
    op.create_table('ifc_viewpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('guid', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('snapshot_key', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['cde_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ifc_viewpoints_file_id'), 'ifc_viewpoints', ['file_id'], unique=False)
    op.create_table('aim_project_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('cde_file_id', sa.UUID(), nullable=False),
    sa.Column('ifc_import_id', sa.UUID(), nullable=True),
    sa.Column('file_category', sa.Text(), nullable=True),
    sa.Column('discipline', sa.Text(), nullable=True),
    sa.Column('is_active_model', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['cde_file_id'], ['cde_files.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ifc_import_id'], ['ifc_imports.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['aim_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aim_project_files_project_id'), 'aim_project_files', ['project_id'], unique=False)
    op.create_table('ifc_elements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('import_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('global_id', sa.Text(), nullable=False),
    sa.Column('ifc_type', sa.Text(), nullable=False),
    sa.Column('element_name', sa.Text(), nullable=True),
    sa.Column('discipline', sa.Text(), nullable=True),
    sa.Column('storey_global_id', sa.Text(), nullable=True),
    sa.Column('storey_name', sa.Text(), nullable=True),
    sa.Column('building_name', sa.Text(), nullable=True),
    sa.Column('property_sets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quantity_sets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('bbox_min_x', sa.Float(), nullable=True),
    sa.Column('bbox_min_y', sa.Float(), nullable=True),
    sa.Column('bbox_min_z', sa.Float(), nullable=True),
    sa.Column('bbox_max_x', sa.Float(), nullable=True),
    sa.Column('bbox_max_y', sa.Float(), nullable=True),
    sa.Column('bbox_max_z', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['import_id'], ['ifc_imports.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ifc_elements_global_id'), 'ifc_elements', ['global_id'], unique=False)
    op.create_index(op.f('ix_ifc_elements_ifc_type'), 'ifc_elements', ['ifc_type'], unique=False)
    op.create_index(op.f('ix_ifc_elements_import_id'), 'ifc_elements', ['import_id'], unique=False)
    op.create_table('pim_project_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('cde_file_id', sa.UUID(), nullable=False),
    sa.Column('ifc_import_id', sa.UUID(), nullable=True),
    sa.Column('discipline', sa.Text(), nullable=True),
    sa.Column('is_active_model', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['cde_file_id'], ['cde_files.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ifc_import_id'], ['ifc_imports.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['pim_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pim_project_files_project_id'), 'pim_project_files', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pim_project_files_project_id'), table_name='pim_project_files')
    op.drop_table('pim_project_files')
    op.drop_index(op.f('ix_ifc_elements_import_id'), table_name='ifc_elements')
    op.drop_index(op.f('ix_ifc_elements_ifc_type'), table_name='ifc_elements')
    op.drop_index(op.f('ix_ifc_elements_global_id'), table_name='ifc_elements')
    op.drop_table('ifc_elements')
    op.drop_index(op.f('ix_aim_project_files_project_id'), table_name='aim_project_files')
    op.drop_table('aim_project_files')
    op.drop_index(op.f('ix_ifc_viewpoints_file_id'), table_name='ifc_viewpoints')
    op.drop_table('ifc_viewpoints')
    op.drop_index(op.f('ix_ifc_selection_groups_file_id'), table_name='ifc_selection_groups')
    op.drop_table('ifc_selection_groups')
    op.drop_index(op.f('ix_ifc_measurements_file_id'), table_name='ifc_measurements')
    op.drop_table('ifc_measurements')
    op.drop_index(op.f('ix_ifc_markers_file_id'), table_name='ifc_markers')
    op.drop_table('ifc_markers')
    op.drop_index(op.f('ix_ifc_imports_cde_file_id'), table_name='ifc_imports')
    op.drop_table('ifc_imports')
    op.drop_index(op.f('ix_gs_tags_file_id'), table_name='gs_tags')
    op.drop_table('gs_tags')
    op.drop_index(op.f('ix_cde_pending_file_shares_file_id'), table_name='cde_pending_file_shares')
    op.drop_index(op.f('ix_cde_pending_file_shares_email'), table_name='cde_pending_file_shares')
    op.drop_table('cde_pending_file_shares')
    op.drop_index(op.f('ix_cde_file_shares_token'), table_name='cde_file_shares')
    op.drop_index(op.f('ix_cde_file_shares_shared_with'), table_name='cde_file_shares')
    op.drop_index(op.f('ix_cde_file_shares_file_id'), table_name='cde_file_shares')
    op.drop_table('cde_file_shares')
    op.drop_index(op.f('ix_cde_pending_folder_shares_folder_id'), table_name='cde_pending_folder_shares')
    op.drop_index(op.f('ix_cde_pending_folder_shares_email'), table_name='cde_pending_folder_shares')
    op.drop_table('cde_pending_folder_shares')
    op.drop_index(op.f('ix_cde_folder_shares_token'), table_name='cde_folder_shares')
    op.drop_index(op.f('ix_cde_folder_shares_shared_with'), table_name='cde_folder_shares')
    op.drop_index(op.f('ix_cde_folder_shares_folder_id'), table_name='cde_folder_shares')
    op.drop_table('cde_folder_shares')
    op.drop_index(op.f('ix_cde_files_owner_id'), table_name='cde_files')
    op.drop_index(op.f('ix_cde_files_folder_id'), table_name='cde_files')
    op.drop_table('cde_files')
    op.drop_index(op.f('ix_pim_scope_items_project_id'), table_name='pim_scope_items')
    op.drop_index(op.f('ix_pim_scope_items_discipline_id'), table_name='pim_scope_items')
    op.drop_table('pim_scope_items')
    op.drop_index(op.f('ix_cde_folders_parent_id'), table_name='cde_folders')
    op.drop_index(op.f('ix_cde_folders_owner_id'), table_name='cde_folders')
    op.drop_index(op.f('ix_cde_folders_discipline_id'), table_name='cde_folders')
    op.drop_table('cde_folders')
    op.drop_table('aim_project_members')
    op.drop_index(op.f('ix_role_permissions_submodule_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_module_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_pim_scope_disciplines_project_id'), table_name='pim_scope_disciplines')
    op.drop_table('pim_scope_disciplines')
    op.drop_table('pim_project_members')
    op.drop_index(op.f('ix_aim_projects_workspace_id'), table_name='aim_projects')
    op.drop_table('aim_projects')
    op.drop_index(op.f('ix_submodules_module_id'), table_name='submodules')
    op.drop_table('submodules')
    op.drop_table('pim_workspace_members')
    op.drop_index(op.f('ix_pim_projects_workspace_id'), table_name='pim_projects')
    op.drop_table('pim_projects')
    op.drop_index(op.f('ix_invitations_token'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_email'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_table('aim_workspace_members')
    op.drop_index(op.f('ix_user_platform_permissions_user_id'), table_name='user_platform_permissions')
    op.drop_table('user_platform_permissions')
    op.drop_index(op.f('ix_storage_usage_user_id'), table_name='storage_usage')
    op.drop_table('storage_usage')
    op.drop_table('roles')
    op.drop_index(op.f('ix_pim_workspaces_owner_id'), table_name='pim_workspaces')
    op.drop_table('pim_workspaces')
    op.drop_index(op.f('ix_pim_subscriptions_user_id'), table_name='pim_subscriptions')
    op.drop_table('pim_subscriptions')
    op.drop_table('modules')
    op.drop_index(op.f('ix_coupons_code'), table_name='coupons')
    op.drop_table('coupons')
    op.drop_index(op.f('ix_cde_naming_codes_owner_id'), table_name='cde_naming_codes')
    op.drop_index(op.f('ix_cde_naming_codes_category'), table_name='cde_naming_codes')
    op.drop_table('cde_naming_codes')
    op.drop_index(op.f('ix_cde_groups_owner_id'), table_name='cde_groups')
    op.drop_table('cde_groups')
    op.drop_index(op.f('ix_aim_workspaces_owner_id'), table_name='aim_workspaces')
    op.drop_table('aim_workspaces')
    op.drop_index(op.f('ix_aim_subscriptions_user_id'), table_name='aim_subscriptions')
    op.drop_table('aim_subscriptions')
    op.drop_index(op.f('ix_work_packages_project_id'), table_name='work_packages')
    op.drop_table('work_packages')
    op.drop_index(op.f('ix_vendors_vendor_code'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_cognito_sub'), table_name='users')
    op.drop_table('users')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_scheduling_tasks_project_id'), table_name='scheduling_tasks')
    op.drop_index(op.f('ix_scheduling_tasks_order'), table_name='scheduling_tasks')
    op.drop_table('scheduling_tasks')
    op.drop_index(op.f('ix_scheduling_task_element_links_task_id'), table_name='scheduling_task_element_links')
    op.drop_index(op.f('ix_scheduling_task_element_links_project_id'), table_name='scheduling_task_element_links')
    op.drop_table('scheduling_task_element_links')
    op.drop_index(op.f('ix_qto_custom_items_project_id'), table_name='qto_custom_items')
    op.drop_table('qto_custom_items')
    op.drop_index(op.f('ix_materials_material_code'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_ifc_meetings_owner_type'), table_name='ifc_meetings')
    op.drop_index(op.f('ix_ifc_meetings_owner_id'), table_name='ifc_meetings')
    op.drop_table('ifc_meetings')
    op.drop_index(op.f('ix_equipment_equipment_code'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_employees_employee_code'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_cost_items_project_id'), table_name='cost_items')
    op.drop_table('cost_items')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
