"""add rbac tables

Revision ID: 5df22ff4a934
Revises: 
Create Date: 2026-09-29 15:27:03.655035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5df22ff4a934'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('razorpay_order_id', sa.Text(), nullable=False),
    sa.Column('razorpay_payment_id', sa.Text(), nullable=True),
    sa.Column('transaction_id', sa.Text(), nullable=True),
    sa.Column('payment_method', sa.Text(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('product_type', sa.Text(), nullable=False),
    sa.Column('plan', sa.Text(), nullable=False),
    sa.Column('billing_period', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_razorpay_order_id'), 'orders', ['razorpay_order_id'], unique=True)
    op.create_index(op.f('ix_orders_razorpay_payment_id'), 'orders', ['razorpay_payment_id'], unique=False)
    op.create_index(op.f('ix_orders_transaction_id'), 'orders', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_transaction_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_razorpay_payment_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_razorpay_order_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
